name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.20.0
      - run: npm install
      - run: npm run build
      - run: npm start
      - run: npm run test:cypress
